import streamlit as st
import pandas as pd
import plotly.express as px
from PIL import Image
import pickle

# ==========================================
# PAGE CONFIGURATION
# ==========================================
st.set_page_config(
    page_title="Cluster Analysis Dashboard",
    layout="wide"
)

# ==========================================
# CUSTOM CSS
# ==========================================
st.markdown("""
<style>

/* FIX TOP SPACING */
.block-container {
    padding-top: 4rem;
    padding-left: 2rem;
    padding-right: 2rem;
    padding-bottom: 2rem;
}

/* Main title */
.main-title {
    text-align: center;
    font-size: 42px;
    font-weight: bold;
    color: #333333;
    margin-bottom: 25px;
}

/* Section headers */
.section-header {
    text-align: center;
    font-size: 28px;
    font-weight: bold;
    color: #555555;
    margin-top: 10px;
    margin-bottom: 15px;
}

/* Scrollable summary box */
.scrollable-summary {
    height: 420px;
    overflow-y: auto;
    border: 1px solid #cccccc;
    border-radius: 10px;
    padding: 15px;
    background-color: #f9f9f9;
}

</style>
""", unsafe_allow_html=True)

# ==========================================
# DISCLAIMER
# ==========================================
st.warning("""
⚠️ DISCLAIMER: This application is developed for educational and portfolio demonstration purposes only.

The clustering predictions and visualizations generated by this system are NOT intended for medical diagnosis, treatment, or healthcare decision-making.

Always consult a qualified healthcare professional for medical advice or diagnosis.
""")

# ==========================================
# LOAD MODEL & DATA
# ==========================================

# Load KMeans model
with open('kmeans_model.pkl', 'rb') as model_file:
    kmeans = pickle.load(model_file)

# Load scaler
with open('scaler.pkl', 'rb') as scaler_file:
    scaler = pickle.load(scaler_file)

# Load PCA visualization data
pca_2d_df = pd.read_excel('pca_2d.xlsx')

# Load cluster analysis table
cluster_analysis = pd.read_excel('cluster_analysis.xlsx')

# Load cluster summaries
try:
    with open('cluster_summaries.pkl', 'rb') as summary_file:
        cluster_summaries = pickle.load(summary_file)

except FileNotFoundError:
    cluster_summaries = None
    st.error("Cluster summaries file not found.")

# ==========================================
# LOAD IMAGES
# ==========================================

sidebar_image = Image.open('PIC3.png')
main_image = Image.open('Pic4.png')

# ==========================================
# SIDEBAR
# ==========================================

st.sidebar.image(sidebar_image, use_container_width=True)

st.sidebar.title("Cluster Visualization")

st.sidebar.info("""
⚠️ Educational Use Only

This dashboard is designed for learning and portfolio purposes only.
""")

# ==========================================
# USER INPUTS
# ==========================================

numeric_features = [
    'age',
    'trestbps',
    'chol',
    'thalch',
    'oldpeak',
    'ca'
]

categorical_options = {
    'sex': ['Female', 'Male'],
    'dataset': ['Cleveland', 'Hungary', 'Switzerland', 'VA Long Beach'],
    'cp': ['asymptomatic', 'atypical angina', 'non-anginal', 'typical angina'],
    'fbs': ['False', 'True'],
    'restecg': ['lv hypertrophy', 'normal', 'st-t abnormality'],
    'exang': ['False', 'True'],
    'slope': ['downsloping', 'flat', 'upsloping'],
    'thal': ['fixed defect', 'normal', 'reversable defect'],
    'Heart Disease Stage': ['0', '1', '2', '3', '4']
}

# Store user inputs
user_inputs = {}

# Numeric inputs
for feature in numeric_features:

    user_inputs[feature] = st.sidebar.number_input(
        feature,
        value=0.0
    )

# Categorical inputs
for feature, options in categorical_options.items():

    selected_value = st.sidebar.selectbox(
        feature,
        options
    )

    # One-hot encoding
    for option in options:

        user_inputs[f"{feature}_{option}"] = (
            1 if selected_value == option else 0
        )

# Convert to DataFrame
input_df = pd.DataFrame([user_inputs])

# ==========================================
# MAIN TITLE
# ==========================================

st.markdown(
    '<div class="main-title">Cluster Analysis with PCA Visualization</div>',
    unsafe_allow_html=True
)

# ==========================================
# MAIN IMAGE
# ==========================================

st.image(main_image, use_container_width=True)

# ==========================================
# FIRST ROW
# ==========================================

left_col, right_col = st.columns(2)

# ==========================================
# PCA VISUALIZATION
# ==========================================

with left_col:

    st.markdown(
        '<div class="section-header">Cluster Visualization</div>',
        unsafe_allow_html=True
    )

    fig = px.scatter(
        pca_2d_df,
        x='PCA1',
        y='PCA2',
        color='Cluster',
        title="Clusters Visualized with PCA",
        labels={
            'PCA1': 'PCA Component 1',
            'PCA2': 'PCA Component 2'
        },
        template='plotly'
    )

    st.plotly_chart(fig, use_container_width=True)

# ==========================================
# CLUSTER SUMMARIES
# ==========================================

with right_col:

    st.markdown(
        '<div class="section-header">Cluster Summaries</div>',
        unsafe_allow_html=True
    )

    summary_content = '<div class="scrollable-summary">'

    if isinstance(cluster_summaries, str):

        summary_content += f"<p>{cluster_summaries}</p>"

    elif cluster_summaries:

        for key, value in cluster_summaries.items():

            summary_content += (
                f"<p><strong>Cluster {key}</strong>: {value}</p>"
            )

    else:

        summary_content += "<p>No cluster summaries available.</p>"

    summary_content += "</div>"

    st.markdown(summary_content, unsafe_allow_html=True)

# ==========================================
# SECOND ROW
# ==========================================

second_left_col, second_right_col = st.columns(2)

# ==========================================
# CLUSTER PREDICTION
# ==========================================

with second_left_col:

    st.subheader("Determine Your Cluster")

    if st.button("Cluster Me"):

        # Scale the input
        scaled_input = scaler.transform(input_df)

        # Predict cluster
        cluster_id = kmeans.predict(scaled_input)[0]

        st.success(f"You belong to Cluster {cluster_id}.")

# ==========================================
# CLUSTER TABLE
# ==========================================

with second_right_col:

    st.subheader("Cluster Analysis Table")

    st.dataframe(
        cluster_analysis.head(),
        height=212,
        use_container_width=True
    )

# ==========================================
# FOOTER
# ==========================================

st.markdown("---")

st.caption("""
This dashboard visualizes clustering patterns using PCA and K-Means clustering.

Created for educational, analytical, and portfolio demonstration purposes only.
""")

# ==========================================
# RUN COMMAND
# ==========================================

# streamlit run K_Means.py
